"""added Payment.currency column

Revision ID: cef96bcac616
Revises: 938b7f260e23
Create Date: 2021-03-31 16:14:17.372114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef96bcac616'
down_revision = '938b7f260e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('currency', sa.String(), nullable=True))
    op.execute("UPDATE payments SET currency='RUB'")
    op.alter_column('payments', 'currency', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'currency')
    # ### end Alembic commands ###
